export enum AuditAction {
    AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
    AUTH_LOGOUT = 'AUTH_LOGOUT',
    AUTH_REGISTER = 'AUTH_REGISTER',
    AUTH_PASSWORD_RESET = 'AUTH_PASSWORD_RESET',
    
    PRODUCT_CREATED = 'PRODUCT_CREATED',
    PRODUCT_UPDATED = 'PRODUCT_UPDATED',
    PRODUCT_DELETED = 'PRODUCT_DELETED',
    
    ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
    ORDER_COURIER_UPDATED = 'ORDER_COURIER_UPDATED',
    
    USER_ROLE_UPDATED = 'USER_ROLE_UPDATED',
    USER_STATUS_UPDATED = 'USER_STATUS_UPDATED',
    
    CATEGORY_CREATED = 'CATEGORY_CREATED',
    CATEGORY_UPDATED = 'CATEGORY_UPDATED',
    CATEGORY_DELETED = 'CATEGORY_DELETED',
    
    COUPON_CREATED = 'COUPON_CREATED',
    COUPON_UPDATED = 'COUPON_UPDATED',
    COUPON_DELETED = 'COUPON_DELETED',
    
    SETTING_UPDATED = 'SETTING_UPDATED',
}
